version: '2'
services:
  skjserver:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - ./srv:/app
      - ./dist:/dist
      - ./log:/log
    environment:
      - MONGO_URL=mongodb://192.168.0.1:27018/skj
      - listenport=3100
      - tcpport=52341
    links:
      - mongodb
    ports:
       - "3100:3100"
       - "52341:52341"
    expose:
       - "3100"
       - "52341"
  mongodb:
    image:  mongo:3.4
    restart: always
    expose:
       - "27018"
    volumes:
       - "/var/db100/dbdata:/data/db -d"
    ports:
       - "27018:27017"
